### ISSUE TITLE
No schema comments?

### ISSUE THREAD

**Issue by timneedham** [ozum/pg-structure#10]
Hi,

Great project and perfect for what we need... one small thing, there doesn't seem to be support for accessing schema comments, something like:

```schema.comment: string```

**A query such as:**

```
select nspname as schema_name, obj_description(oid, 'pg_namespace') as schema_comment
from pg_namespace;
```

Would do the trick I think?

**Comment by ozum** [comment]
Hi,

I'm on a business trip with limited accessibility , I'll look into that when I return.

Regards,

**Comment by ozum** [comment]
Hi,

`Schema#comment` and `Schema#description` attributes are added as of version 4.

**Comment by timneedham** [comment]
Great stuff, thank you!
