### ISSUE TITLE
Deprecation warning from pg

### ISSUE THREAD

**Issue by cymen** [ozum/pg-structure#13]
```
(node:87541) DeprecationWarning: Using the automatically created return value from client.query as an event emitter is deprecated and will be removed in pg@7.0. Please see the upgrade guide at https://node-postgres.com/guides/upgrading
```
Probably https://node-postgres.com/guides/upgrading#client-query-on

**Comment by ozum** [comment]
Thanks for the notice. Upgraded `node-postgres` to version 7 and fixed as necessary to prevent depreciation warnings.

Please upgrade to latest version of `pg-structure`
