### ISSUE TITLE
isPrimaryKey returns undefined for column that is a primary key

### ISSUE THREAD

**Issue by egeste** [ozum/pg-structure#2]
Per my conversation with myself in https://github.com/ozum/sequelize-pg-generator/issues/9, pg-structure fails to indicate that a primary key column is a primary key via the `isPrimaryKey` interface.

According to the PostgreSQL documentation:

`Technically, a primary key constraint is simply a combination of a unique constraint and a not-null constraint.`
http://www.postgresql.org/docs/9.0/static/ddl-constraints.html#AEN2494

So a potential workaround may be to check the state of unique and allowNull on a column.

```javascript
Column.prototype.isPrimaryKey = function () {
    return (this.unique() !== null && !this.allowNull());
}
```

**Comment by ozum** [comment]
@egeste Thank you for using this library. You are right. Technically, a primary key constraint is simply a combination of a unique constraint and a not-null constraint. So every primary key is a *unique not null constraint*. However, this is important, not every *unique not null constraint* is a primary key.

There may be more than one *unique not null constraints* in a table, but only one of them is a primary key of that table.

As per http://www.postgresql.org/docs/9.0/static/ddl-constraints.html#AEN2494

> Technically, a primary key constraint is simply a combination of a unique constraint and a not-null constraint.
...
A table can have at most one primary key. (There can be any number of unique and not-null constraints, which are functionally the same thing, but only one can be identified as the primary key.) Relational database theory dictates that every table must have a primary key.

Unfortunately this assumption is not correct:

    Column.prototype.isPrimaryKey = function () {
        return (this.unique() !== null && !this.allowNull());
    }

IMHO you probably should explicitly mark your primary keys in your database designs. Also as a side note a primary key may contain more than one column.

Hope this helps,

Sorry, I couldn't add this check to the module.

Best Regards,

**Comment by egeste** [comment]
Thanks for taking a critical look into the issue. Unfortunately this still leaves me with the problem of my auto generated models not flagging my primary key columns. How can I indicate that a column is a primary key such that this library will detect it?

**Comment by ozum** [comment]
Hmm. Is there a particular reason why your actual database does not mark primary keys as primary keys? Could you please give details about your design decisions?

**Comment by egeste** [comment]
After doing some research and experimentation I discovered that attempting to add a column marked as primaryKey after the table is created just doesn't work. I don't know whether the failure occurred in postgres or in the Sequelize::addColumn method - but defining the id field as primary key at the time of table creation resulted in the column being properly marked as a primary key - which was subsequently properly flagged in pg-structure. Sorry for the bogus tickets. Thanks for the help.

**Comment by ozum** [comment]
Your welcome. Most probably it is not a postgres issue, because setting a column as primary key during creation or modification does not differ in PostgreSQL. However, as simplest case, a column cannot altered as primary key if there are some data in the table which prevents the column being unique.

For example table below; record_no cannot be changed as primary key.

    record_no      name
    ---------      ----
      1            George
      1            Nathan
      2            Sarah

**Comment by egeste** [comment]
@ozum in my case, there was no data in the table - which leads me to believe it's a bug in `Sequelize::addColumn`
