### ISSUE TITLE
Is there a way to get precision and scale out of numeric column type?

### ISSUE THREAD

**Issue by viktor-ku** [ozum/pg-structure#23]
Hi. 

Currently I am doing this

```js
  const db = await pgStructure(connection)

  const tables = db.schemas.get('public').tables

  for (const table of tables.values()) {
    const columns = table.columns

    for (const column of columns.values()) {
      const colType = columns.get(column.name).type

      if (colType === 'numeric') {
        console.log([table.name, column.name].join('.'), colType)
      }
    }
  }
```

Works great, as output I get correct tables and columns. However it shows just `numeric` without precision or scale to it. I'd like to see `numeric(10, 2)` for example.

Is it possible?

Thanks

**Comment by ozum** [comment]
Hi @viktor-ku ,

Yes, please see:
http://www.pg-structure.com/api/Column/#Column+precision
http://www.pg-structure.com/api/Column/#Column+scale

**Comment by viktor-ku** [comment]
@ozum thanks a ton! Went through that page a few times but still somehow missed these props. Just found this lib today, very useful!

**Comment by ozum** [comment]
I miss too, I need to revisit docs to check whether it is available.

Currently I'm working on a TypeScript version of the library. It would be used easier if you are using TypeScript.

**Comment by viktor-ku** [comment]
@ozum Typescript is exactly what I am using for everything nowadays. Was also thinking of making a d.ts file for this project one day. Are you rewriting the whole thing in ts or just `d.ts` file?

**Comment by ozum** [comment]
@viktor-ku. I'm rewriting whole library.

If you create some schema or some files based on your pg database, you may want to see pg-generator (www.pg-generator.com).
