### ISSUE TITLE
Possible to grab functions and triggers - Question

### ISSUE THREAD

**Issue by PavithraNavaneeth** [ozum/pg-structure#27]
Hi,
Could you please clarify if its feasible to grab the triggers, sequences and functions defined in the schema ?

Thanks !

**Comment by ozum** [comment]
Hi @PavithraNavaneeth, 

Unfortunately currently not. If you could provide full-fledged SQL queries to fetch those. I will add them to next version.

**Comment by exit9** [comment]
It's not full-fledged SQL queries, but anyway: 

SELECT * FROM pg_trigger

SELECT * FROM pg_sequences

SELECT routines.routine_name, parameters.data_type, parameters.ordinal_position
FROM information_schema.routines
    LEFT JOIN information_schema.parameters ON routines.specific_name=parameters.specific_name
WHERE routines.specific_schema='public'
ORDER BY routines.routine_name, parameters.ordinal_position;

**Comment by ozum** [comment]
Thanks @exit9, it could be a starting point for me to work when I have time.

**Comment by jayarjo** [comment]
Would be great to be able to grab other kinds of constraints as well.

**Comment by ozum** [comment]
It is very helpful if someone provide a single and efficient SQL query which provides every details of required object (constraint, function etc...)

I can implement that database object easily.

Otherwise it is very hard for me to research an efficient SQL for each database object.

**Comment by jayarjo** [comment]
This is SQL that I currently use to grab CHECK constraints, it doesn't include function name though:

```sql
SELECT pgc.conname      AS constraint_name, 
       ccu.table_schema AS table_schema, 
       ccu.table_name, 
       ccu.column_name, 
       pgc.consrc       AS condition 
FROM   pg_constraint pgc 
       JOIN pg_namespace nsp 
         ON nsp.oid = pgc.connamespace 
       LEFT JOIN information_schema.constraint_column_usage ccu 
              ON pgc.conname = ccu.constraint_name 
WHERE  table_schema = 'public' 
       AND contype = 'c' 
ORDER  BY constraint_name; 
```

**Comment by jayarjo** [comment]
And here's the one to grab triggers:

```sql
SELECT trigger_name, 
       event_object_schema AS table_schema, 
       event_manipulation  AS event, 
       event_object_table  AS table_name, 
       action_condition, 
       action_timing 
FROM   information_schema.triggers 
WHERE  trigger_schema = 'public' 
```

**Comment by ozum** [comment]
I'm leaving this thread open, and wait some SQL pile up. In a spare time, I will try to implement as much as possible in one go.

**Comment by straldev** [comment]
I use this to grab function info
```sql
SELECT pg_proc.proname                                            AS function_name,
       pg_namespace.nspname                                       AS schema_name,
       pg_catalog.pg_get_function_identity_arguments(pg_proc.oid) AS function_args,
       pg_catalog.pg_get_functiondef(pg_proc.oid)                 AS function_source
FROM pg_catalog.pg_proc
         JOIN pg_catalog.pg_namespace ON pg_namespace.oid = pg_proc.pronamespace
WHERE nspname = $1
  AND probin IS NULL;
```

You've probably already implemented everything this query provides, but while I'm at, this is what I use to collect attribute and value info on all enums, custom composite types, and tables.
```sql
SELECT pg_type.oid AS type_id,
       pg_namespace.nspname AS schema_name,
       pg_catalog.format_type(pg_type.oid, null) AS type_name,
       pg_type.typtype AS type_type,
       (SELECT pg_catalog.format_type(base_type.oid, null) FROM pg_type AS base_type WHERE base_type.oid = pg_type.typbasetype) AS base_type,
       (SELECT relkind FROM pg_class WHERE pg_class.oid = pg_type.typrelid) AS rel_type,
       (SELECT array_agg(ROW (attname, pg_catalog.format_type(attr_type.oid, null), attnum))
        FROM pg_attribute
               JOIN pg_type AS attr_type ON attr_type.oid = atttypid
        WHERE pg_attribute.attrelid = pg_type.typrelid AND pg_attribute.attnum > 0) AS composition,
       (SELECT array_agg(enumlabel ORDER BY enumlabel) FROM pg_enum WHERE pg_type.oid = pg_enum.enumtypid) AS enum_values

FROM pg_type
       JOIN pg_namespace ON pg_namespace.oid = pg_type.typnamespace
WHERE nspname = $1;
```

**Comment by straldev** [comment]
Actually, @ozum if you provide some requirements I'm happy to write the SQL to collect whatever info is needed for triggers, functions, etc.

**Comment by ozum** [comment]
> Actually, @ozum if you provide some requirements I'm happy to write the SQL to collect whatever info is needed for triggers, functions, etc.

@straldev, I would like to, but currently I don't know what details users need. I would examine some SQL Manager applications to get what would be needed. I need some time though, because I'm busy nowadays.

After that, I would really appreciate if you could help.

**Comment by straldev** [comment]
Makes sense! Reach out when you're ready and I'll help if I can.

**Comment by jayarjo** [comment]
@ozum in fact I think you could start with obvious ones - those that I and @straldev have listed in our selects and then expand if people request more.

**Comment by straldev** [comment]
@ozum I need to get functions added and issue #53 resolved in a couple of days. I understand that timeline doesn’t work on your end so I intend to implement them myself. I know you’re busy, but if you are able to provide any direction or requirements I would be happy to code this in a way that you can make use of.

If I have time I will implement triggers and sequences as well.

**Comment by ozum** [comment]
@straldev, I'm working on it.

**Comment by ozum** [comment]
I got `ERROR:  "array_agg" is an aggregate function` from following query:

```sql
SELECT pg_proc.proname                                            AS function_name,
       pg_namespace.nspname                                       AS schema_name,
       pg_catalog.pg_get_function_identity_arguments(pg_proc.oid) AS function_args,
       pg_catalog.pg_get_functiondef(pg_proc.oid)                 AS function_source
FROM pg_catalog.pg_proc
         JOIN pg_catalog.pg_namespace ON pg_namespace.oid = pg_proc.pronamespace
WHERE nspname = $1
  AND probin IS NULL;
```

Function part needs quite planning, since functions are very complicated DB objects. There are three major parts at least: Argument details, return details and function itself.

For the beginning, I need a query similar to this:

|function schema|function name|function description|function source|argument name|argument position|argument type oid|

Also what do you think about return details?

**Comment by straldev** [comment]
We use that query on our prod server which is running version 9.6, testing it in version 12 gives that error. I'll work on a new query that works for 12.

The argument values you're after of course have a 1-many relationship with the function. Do you want duplicate rows for the function for each argument, or do you want to aggregate those argument values into an array? Perhaps using jsonb. Also the function's language and volatility may be nice details to have as well.

> Also what do you think about return details?
I think the only relevant information we want about the return details is the type, what do you think?

**Comment by straldev** [comment]
@ozum Looks like there are some differences in the pg_proc table between the currently supported versions of postgres (9, 10, 11, 12). Which of these would you like to target? Would it be possible to have different queries based on the version?

**Comment by straldev** [comment]
```sql
select
    pg_namespace.nspname                                       as schema_name,
    pg_proc.proname                                            as function_name,
    pg_catalog.pg_get_functiondef(pg_proc.oid)                 as function_source,
    pg_language.lanname                                        as function_language,
    pg_proc.procost                                            as estimated_execution_cost,
    pg_proc.prorows                                            as estimated_result_rows,
    pg_proc.proleakproof                                       as function_is_leakproof,
    pg_proc.provolatile                                        as function_volatility,
    pg_proc.prorettype                                         as function_return_type,
    pg_proc.provariadic                                        as variadic_argument_type,
    pg_catalog.pg_get_function_identity_arguments(pg_proc.oid) as function_argument_type_names,
    pg_proc.proargtypes                                        as function_input_argument_types,
    format(
            '%s(%s)',
            pg_proc.proname,
            replace(pg_proc.proargtypes::text, ' ', ',')
        )                                                      as function_signature,
    pg_proc.proallargtypes                                     as function_all_arguments,
    pg_proc.proargnames                                        as function_argument_names,
    pg_proc.proargdefaults                                     as function_argument_defaults
from
    pg_catalog.pg_proc
    join pg_catalog.pg_namespace on pg_namespace.oid = pg_proc.pronamespace
    join pg_catalog.pg_language on pg_language.oid = pg_proc.prolang
where
    pg_namespace.nspname = $*
--     pg_proc.proisagg is false -- this is for versions 9 and 10
--     pg_proc.prokind in ('f', 'p', 'w') -- this is for versions 11 and 12
    and pg_proc.probin is null;
```

This should provide most details on the function. I didn't see anything about a function description though.
The two commented WHERE operations are the only differences between the PG versions. I'm not sure yet if there's a way to build the query for both versions, but I'll take a crack at it later today.

Here's the doc page on the pg_proc table:
https://www.postgresql.org/docs/12/catalog-pg-proc.html

Let me know if there's any feedback / issues!

**Comment by ozum** [comment]
> Would it be possible to have different queries based on the version?

> I'm not sure yet if there's a way to build the query for both versions, but I'll take a crack at it later today.

Currently not, but I will think a way to implement it.

**Comment by ozum** [comment]
Last published version `v7.1.0` supports different SQL queries based on major PostgreSQL version.

SQL directory is divided by version numbers. Greatest version equal or less than pg version is used.

For example for following directory structure,

```ts
module-files
|- sql
  |- 9
  |- 11
```

PostgreSQL 9 and 10 use "9" directory.
PostgreSQL 11 and 12 use "11" directory.

**Comment by ozum** [comment]
@straldev @jayarjo I added function support. There are lots of edge cases, so it took some time to implement.

See:
- `src/pg-structure/base/func.ts` 
- `src/pg-structure/function-arguments.ts`

Example:
```ts
db.schemas.get("public").functions.get("myFunction").arguments[0].type.name;
```

Could you please test if it works?

**Comment by ozum** [comment]
v7.2.2 adds trigger support with `Trigger` class.

Example:

```ts
db.get("public.someTable").triggers[0].function.name;
```

**Comment by straldev** [comment]
Very nice! I will try this out later today and let you know if I run into any issues. Many thanks for taking care of this!
