### ISSUE TITLE
Could not find a declaration file for module 'pg'

### ISSUE THREAD

**Issue by emlai** [ozum/pg-structure#32]
Hello! I upgraded from pg-structure v4.2.2 to v5.6.0 and I'm now getting the following TypeScript error:

```
node_modules/pg-structure/dist/index.d.ts:1:38 - error TS7016: Could not find a declaration file for module 'pg'. 'C:/Users/emlai/src/dbviz/node_modules/pg/lib/index.js' implicitly has an 'any' type.
  Try `npm install @types/pg` if it exists or add a new declaration (.d.ts) file containing `declare module 'pg';`

1 import { Client, ClientConfig } from "pg";
                                       ~~~~
```

I checked the breaking changes and readme but couldn't find anything regarding this.

The error is originating in `node_modules/pg-structure` so I think this should be fixed on pg-structure's side (my project doesn't care about pg typings). I believe moving "@types/pg" from "devDependencies" to "dependencies" would fix this. What do you think?

**Comment by ozum** [comment]
Most probably it will solve it. I will look it.
