### ISSUE TITLE
Serialize to JSON in v5

### ISSUE THREAD

**Issue by emlai** [ozum/pg-structure#33]
I used to do `pgStructure.serialize(db)` to convert my database structure to a JSON string (to send from server to client) in v4, but the `serialize` method doesn't seem to be available anymore in v5.

I tried to look for an alternative in the breaking changes and API documentation but couldn't find anything. Also tried to do a simple `JSON.stringify` but got a `Converting circular structure to JSON` error.

Is there some alternative API that I'm not aware of or is something like this going to be added in v5? Thanks!

**Comment by ozum** [comment]
Actually, it is not implemented. I need to think an alternative approach to serialization, because serialization of circular structures make refactoring difficult.

I think serializing sql query results and recreating  objects from those would be a scalable solution.

**Comment by ozum** [comment]
@emlai I added a new implementation for serialization / deserialization and a test. Could you please check if it works as expected.

Usage:

```ts
const serialized = db.serialize();
const otherDb = deserialize(serialized);
```

**Comment by emlai** [comment]
Tried that and it works perfectly for my (quite simple) use case. I'll let you know if I run into any problems. Thanks!
