### ISSUE TITLE
tslib module dependency not declared

### ISSUE THREAD

**Issue by backhand** [ozum/pg-structure#34]
Version: 5.7.0

Reproduction:
1. Fresh install using npm install pg-structure@5.7.0)
2. Run suggested demo from frontpage of pg-structure.com (async function demo() ...) replacing login information and table names.

Output:
Error: Cannot find module 'tslib'
Require stack:
- /<snip>/node_modules/pg-structure/dist/index.js
...
    at Object.<anonymous> (/<snip>/node_modules/pg-structure/dist/index.js:3:17)

**Comment by ozum** [comment]
@backhand thanks for the report. `tslib` is added to dependencies. Please update to latest version.

**Comment by backhand** [comment]
Aand it's gone again:
https://github.com/ozum/pg-structure/commit/b4576756aea91e09c5d99ad21ef412de3e083dac#diff-b9cfc7f2cdf78a7f4b91a753d10865a2
