### ISSUE TITLE
tslib module dependency not declared (re-issue)

### ISSUE THREAD

**Issue by backhand** [ozum/pg-structure#36]
Version: 5.10.2

Reproduction:

Fresh install using npm install pg-structure@5.10.2)
Run suggested demo from frontpage of pg-structure.com (async function demo() ...) replacing login information and table names.
Output:
Error: Cannot find module 'tslib'
Require stack:

//node_modules/pg-structure/dist/index.js
...
at Object. (//node_modules/pg-structure/dist/index.js:3:17)

See commit:
https://github.com/ozum/pg-structure/commit/b4576756aea91e09c5d99ad21ef412de3e083dac#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

**Comment by ozum** [comment]
I removed dependency to `tslib` from `pg-structure`, by setting `"importHelpers": false` in `tsconfig.json`.

This error originated from one of the dependencies (`indexable-array`), which is developed by me.

I fixed it too. Please update `pg-structure` to latest version and report if error continues.

Thanks,
