### ISSUE TITLE
Typo on landing page

### ISSUE THREAD

**Issue by vincentdesmares** [ozum/pg-structure#39]
v5 beraking changes. -> v5 breaking changes.

Anyway I love the concept! Congratulation for landing it! It can be super useful to generate a GraphQL schema dynamically.

**Comment by ozum** [comment]
Thanks. @fnando committed a PR for this typo. It will be updated soon.

**Comment by ozum** [comment]
> It can be super useful to generate a GraphQL schema dynamically.

@vincentdesmares, you can check [pg-generator](https://www.pg-generator.com/) to create a generator.

**Please beware**
Currently [pg-generator](https://www.pg-generator.com/) uses previous version of pg-structure, and pg-generator will be completely rewritten, and it will not be backwards compatible. However it could help a lot in current state.
