### ISSUE TITLE
Property 'tables' does not exist on type 'Schema | Entity | Column'.

### ISSUE THREAD

**Issue by brianmcallister** [ozum/pg-structure#40]
I'm just getting started with `pg-structure`, so it could be something that I'm doing wrong, but when I try to set up the basic examples from the documentation, I get the following error:

```bash
⨯ Unable to compile TypeScript:
test.ts:6:42 - error TS2339: Property 'tables' does not exist on type 'Schema | Entity | Column'.
  Property 'tables' does not exist on type 'Entity'.

6   console.log('tables', db.get('public').tables);
```

I tried setting up the most minimal project possible, and I'm able to reproduce. Here's my `package.json` dependencies:

```
"pg-structure": "^5.10.4",
"typescript": "^3.7.4"
```

...and here's the complete file that I'm trying to run:

```js
import pgStructure from 'pg-structure';

(async () => {
  const db = await pgStructure({ database: 'dvdrental' }, { includeSchemas: ['public'] });

  console.log('tables', db.get('public').tables);
})();
```

Interestingly, `db.tables` seems to get all the tables from the `public` schema. It looks like `get` returns a `Schema | Entity | Column`, and `Entity` definitely does not have a `tables` property on it, so I understand why I'm seeing the error.

Am I maybe doing something wrong in my setup here?

**Comment by ozum** [comment]
Hi @brianmcallister, your example is correct as JavaScript, but TypeScript cannot be sure that returned value from `db.get()` (`Schema` or `Entity` or `Column`) has `tables` attribute, because returned value may be an `Entity` or a `Column` which do not have `tables`.

Try one of the below:

```ts
console.log("tables", (db.get("public") as Schema).tables)
```

or

```ts
console.log("tables", db.schemas.get("public").tables)
```

**Comment by brianmcallister** [comment]
Oh yeah, I totally understand why TypeScript is raising that error, I just wanted to check if that was expected behavior.

I suppose my suggestion would be to add a note to the documentation about this issue, and/or tightening up the types so that this error doesn't occur anymore, and/or possibly even removing the `get` method from the `Db` type entirely.

Thanks for taking a look though, and I'm definitely making good use of this package so far!

**Comment by ozum** [comment]
Yes, it is expected behavior. 

I added documentation as you suggested. It will be published soon.

I can't think a way to tighten `get()`, it returns 3 possible types (similar to `lodash.get()`). Any suggestions are welcome.

Also if `get()` is removed, then we lose convenience.

```ts
// with get:
const column = db.get("public.account.name");
// without get:
const column = db.schemas.get("public").tables.get("account").columns.get("name");
``

**Comment by brianmcallister** [comment]
Fair point (and thanks for adding a note to the docs).

My opinion is that I'd be willing to have a slightly more verbose syntax in order to make writing type safe code more convenient. I _could_ write type guard functions, but now it's more 'work' for me. Maybe an API something like this:

```ts
const schema = db.get({ schema: 'public' });
const table = db.get({ table: 'account' });
const column = db.get({ column: 'name' });

// ...which would also allow you to do:
const idColumn = db.get({ schema: 'public', table: 'account', column: 'name' });
```
