### ISSUE TITLE
Typescript Error: Property 'get' does not exist on type 'IndexableArray<Column, "name", "attributeNumber", true>'.

### ISSUE THREAD

**Issue by s888** [ozum/pg-structure#41]
Hi,

I have just come across this module and its seems to be wonderful.
But when I am trying to run the code in typescript I get this error:

```
pgStructure.ts:15:43 - error TS2339: Property 'get' does not exist on type 'IndexableArray<Column, "name", "attributeNumber", true>'.

15     const columnTypeName = (table.columns.get("name") as Column).type.name;
```
Here's the code:

```
import pgStructure, { Column, Entity } from "pg-structure";
async function demo() {
    const db = await pgStructure(
        { database: "db_test", user: "user", password: "user"}, 
        );

    //have to give the schema here else it gives an error. Where to set the schema?
    const table = db.get('test.contact') as Entity;
    const columnNames = table.columns.map(c => c.name);
    //this give an error
    const columnTypeName = (table.columns.get("name") as Column).type.name;
}
```
How to get the column type name in typescript?

Thanks in advance.

**Comment by s888** [comment]
Is this the correct way?
```
const columnTypeName = (db.get('test.contact.name') as Column).type.name;
```

**Comment by ozum** [comment]
@s888, yes the way is correct.

I could not reproduce the error using your code. Could you please provide a sample repo including `DDL` (SQL to create same database as yours), so I could further investigate your problem.

Just a tip:
```ts
// Here, you don't need `as Column`, because `columns.get()` returns type of Column.
const columnTypeName = table.columns.get("name").type.name;

// Here you need `as Column`, because `db.get()` may return several types.
const columnTypeName = (db.get('test.contact.name') as Column).type.name;
```

**Comment by s888** [comment]
> @s888, yes the way is correct.
> 
> I could not reproduce the error using your code. Could you please provide a sample repo including `DDL` (SQL to create same database as yours), so I could further investigate your problem.
> 
> Just a tip:
> 
> ```ts
> // Here, you don't need `as Column`, because `columns.get()` returns type of Column.
> const columnTypeName = table.columns.get("name").type.name;
> 
> // Here you need `as Column`, because `db.get()` may return several types.
> const columnTypeName = (db.get('test.contact.name') as Column).type.name;
> ```

Thanks for your reply. 
Yes I had tried 
```
const columnTypeName = table.columns.get("name").type.name;
```
But i got the same error 
```
error TS2339: Property 'get' does not exist on type 'IndexableArray<Column, "name", "attributeNumber", true>'
```
This works though
```
 const columnTypeName = (db.get('test.contact.name') as Column).type.name;
```
Also, Is there a way to know if the column is 'EnumType', 'CompositeType' or 'BuiltInType'?

**Comment by ozum** [comment]
> But i got the same error.
I could run your code without a warning and error. Could you please provide a sample repo including DDL (SQL to create same database as yours), so I could further investigate your problem.

![image](https://user-images.githubusercontent.com/1497060/74030658-a2acbf00-49c0-11ea-80ca-311fc7b7f6ab.png)

> Also, Is there a way to know if the column is 'EnumType', 'CompositeType' or 'BuiltInType'?

Yes, update `pg-structure` to 5.10.7. (There was typo in previous version).

```ts
import { EnumType, CompositeType, BuiltInType } from "pg-structure";

if (x instanceof EnumType) {}
if (x instanceof CompositeType) {}
if (x instanceof BuiltInType) {}
```
