### ISSUE TITLE
Get details about composite types

### ISSUE THREAD

**Issue by user-devs** [ozum/pg-structure#42]
Hi,

Can I get all the fields along with their datatypes for composite types using this module?

**Comment by ozum** [comment]
Yes, please see https://www.pg-structure.com/nav.02.api/classes/compositetype.html

**Comment by user-devs** [comment]
So if the composite type column is options.
Will this give all the fields of options along with the attributes. Could you please help me with the syntax
```
table.columns.get("options").columns
```
I am trying out the code but I am unable to connect to db (port is not the default port) I am getting this error:
```
TypeError: Cannot read property 'name' of undefined
    at Socket.<anonymous> (xxx/pg/lib/connection.js:130:27)
```
Code snippet that gives error:
```
const db = await pgStructure(
{ database: "xxx", user: "xxx", password: "xxx", port: 1205}
);
```

**Comment by ozum** [comment]
All the fields of composite type of `options` columns.

```ts
const compositeColumns = table.columns.get("options").type.columns;
```

For other error, I need a sample repository to investigate.

**Comment by user-devs** [comment]
> All the columns of composite type from `options` column.
> 
> ```ts
> const compositeColumns = table.columns.get("options").type.columns;
> ```
> 
> For other error, I need a sample repository to investigate.

Thank you. Here it is https://github.com/user-devs/pgs-connect/

**Comment by ozum** [comment]
I cannot reproduce error. The code you provided works as expected.

If you can create a sample with the error in an online environment such as https://codesandbox.io or similar, I can look at it.

**Comment by user-devs** [comment]
> All the columns of composite type from `options` column.
> 
> ```ts
> const compositeColumns = table.columns.get("options").type.columns;
> ```
> 
> For other error, I need a sample repository to investigate.

I get an error ```error TS2339: Property 'columns' does not exist on type 'Type'.``` when I do this in typescript
```
const compositeColumns = (db.get(`testdb.contact.options`) as Column).type.columns
```

**Comment by ozum** [comment]
Please try following:

```ts
const compositeColumns = ((db.get(`testdb.contact.options`) as Column).type as CompositeType).columns

```
