### ISSUE TITLE
includeSchemas doesn't work when used as an Array

### ISSUE THREAD

**Issue by hymanchengo** [ozum/pg-structure#45]
Hi,
when I use includeSchemas as  following, it seems not work properly, the schema length is 0 when I debug it. but ```includeSchemas: 'p%'``` seems good property,it get all schemas that start with p.
but i can't find a way to make followings work. Am I missing something. Thank you for your suggestions. 
``` js
pgStructure({
    host: dbserver,
    database: dbName,
    user: dbUser,
    password: dbPassword
  },
  {includeSchemas: ["public", "test"]})
```

**Comment by ozum** [comment]
@hymanchengo thanks for the report. You are doing right. This is a bug and I fixed it. Please update to latest version from npm. If you encounter the problem again, please reopen the case.

**Comment by hymanchengo** [comment]
perfect! It works now! Thank you!
