### ISSUE TITLE
isEnum to easily distinguish enum columns?

### ISSUE THREAD

**Issue by jayarjo** [ozum/pg-structure#47]
Would be great to have a way to easily distinguish `enum` column, something like `isEnum` would work.

Other than that what would be the recommended way to detect enum columns?

**Comment by ozum** [comment]
Hi,

```ts
import { EnumType } from "pg-structure";
const isEnum = myColumn.type instanceof EnumType;
```

**Comment by ozum** [comment]
Also possible other use cases.

See https://www.pg-structure.com/nav.02.api/classes/enumtype.html#class-enumtype

```ts
if (myColumn.type instanceof EnumType) {
  const enumValues = myColumn.type.values;
}
```
