### ISSUE TITLE
Do not auto close connection when established client is passed to constructor

### ISSUE THREAD

**Issue by jayarjo** [ozum/pg-structure#50]
Do not auto close connection when established client is passed to constructor. Or at least make it possible to opt-out of such behavior. Because obviously if someone passes in a client, he/she uses it outside somewhere and simply doesn't want to create an extra connection.

**Comment by ozum** [comment]
I added this feature yesterday. `pg-structure` should keep connection if it is provided an open connection.

Could you please first try latest version without any option and give feedback.

If it does not help, I just added `keepConnection` option, set it `true`.

**Comment by jayarjo** [comment]
That worked, thanks!

**Comment by ozum** [comment]
Does it work without option?

**Comment by jayarjo** [comment]
It does yes, sorry.
