### ISSUE TITLE
Retrieve the type of the geometry column (e.g. Point, LineString, etc)

### ISSUE THREAD

**Issue by jayarjo** [ozum/pg-structure#51]
I'm using `pg-structure` for seeding values into quite complex Postgres database (with PostGIS plugin) having various geometry types. So what I lack is definition of the type of geometry column (e.g. whether it is a Point, or LineString, or Polygon). Does `pg-structure` return it somewhere in the type data structure, or not supported at the moment?

**Comment by ozum** [comment]
Unfortunately, pg-structure does not support PostGIS.

**Comment by ozum** [comment]
But you can examine a previous PR of @nikcub https://github.com/ozum/pg-structure/pull/4 

It cannot be merged, because it fails if PostGIS is not added to database. It may help you, if you copy changes to your local installation.
