### ISSUE TITLE
Error opening database when column has table type

### ISSUE THREAD

**Issue by straldev** [ozum/pg-structure#53]
I have a table called "locale" and I have a mat view that has a column of type "locale". That is, the column's type is the same type as the table (since all tables are also types in pg).

When I open the database for introspection:
```const db = await pgStructure(config); ```

I get this error
``` 
Error: 'locale' cannot be found in CompositeType's name.
at Proxy.get (<omitted path>/node_modules/indexable-array/src/index.ts:735:13)
at new Column (<omitted path>/node_modules/pg-structure/src/pg-structure/column.ts:35:87)
at <omitted path>/node_modules/pg-structure/src/index.ts:239:25
at Array.forEach (<anonymous>)
at addColumns (<omitted path>/node_modules/pg-structure/src/index.ts:234:8)
at Object.pgStructure [as default] (<omitted path>/node_modules/pg-structure/src/index.ts:405:3)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

I suspect pgStructure is only considering non-table types when building columns. If so, I propose table-types are also considered.

I believe this is the line of code that is only checking non-table types when creating a column.
https://github.com/ozum/pg-structure/blob/d0512e5a2edf852765661bab1cf2e89cf35d1fdd/src/pg-structure/column.ts#L35

**Comment by ozum** [comment]
@straldev, could you please provide a very minimal DDL, so I can work on it.

**Comment by straldev** [comment]
```sql
create table public.table_type (
    id   serial not null,
    name text   not null,
    primary key (id)
);

create table public.dep_on_table (
    id     serial     not null,
    t_type table_type not null,
    primary key (id)
);
```

pgStructure works if you create the `table_type` table, but once you create the `dep_on_table` table it fails. Of course now the error is "Error: 'table_type' cannot be found in CompositeType's name."
```const db = await pgStructure(config, {includeSchemas: ['public']});```

**Comment by ozum** [comment]
Yes, current SQL does not considers tables as a type, but it should be.

Do you have a suggestion at hand for the `/module-files/sql/type.sql` for adding tables as type?

**Comment by straldev** [comment]
https://github.com/ozum/pg-structure/blob/d0512e5a2edf852765661bab1cf2e89cf35d1fdd/module-files/sql/type.sql#L53

You could change line 53 to
```sql c.relkind IN ('c', 'r', 'v', 'm')```

Per https://www.postgresql.org/docs/current/catalog-pg-class.html on the relkind column:
> r = ordinary table, i = index, S = sequence, t = TOAST table, v = view, m = materialized view, c = composite type, f = foreign table, p = partitioned table, I = partitioned index

So that change would add tables, views and mat views to the composite types that are already getting included. Pretty sure there are no use case for indexes, sequences, toast tables, or partial indexes to be used as types. Not sure about foreign tables or partitioned tables.

**Comment by straldev** [comment]
@ozum after some reflection I think it might be better to stop filtering by relkind in the query all together. Instead, you could include the relkind as part of the query's projection, and then filter the query results based on an optional config value. In this way, users can select which relkinds they want to include and we can get additional relkinds added without breaking backwards compatibility.

To accomplish this, I propose adding a `includeRelKinds` property to the `Options` interface, and have it's default set to `'c'`. This would cause the lib to behave as it does today, unless someone explicitly adds extra relkinds.

**Comment by ozum** [comment]
This should be fixed with latest release. Now you can access using `Schema.types` and `Schema.typesIncludingEntities` methods. Also you can access underlying table, mv, or view from `Type.entity` attribute.

An Example:

```
const table = db.get("public.dep_on_table.t_type").type.entity;
```
