### ISSUE TITLE
when table is partitioned. db.entities can't load the table

### ISSUE THREAD

**Issue by hymanchengo** [ozum/pg-structure#54]
Dear Ozum,
   I have upgraded pg-structure to lastest version:current is 7.2.3. Today I ran into an error. After some debug effort, I found the problem was caused by a partitioned table.  the error arises when call `db.entities.get(row.tableOid, { key: "oid" });`。
```
function addIndexes(db, rows) {
    rows.forEach((row) => {
       // problem occurs when call db.entities. it can't get the partition table
        const parent = db.entities.get(row.tableOid, { key: "oid" });
        const index = new pg_structure_1.default({ ...row, parent });
        ..... (leave out  for simple)
    });
}
```
I would appreciate it if you could take a moment to look at it and maybe fix it. Thank you!

**Comment by ozum** [comment]
Could you please provide a sample `DDL` which produces given error? So I can examine the problem.

**Comment by hymanchengo** [comment]
```sql
SELECT
  c.oid AS "oid",
  c.relnamespace AS "schemaOid",
  c.relkind AS "kind",
  c.relname AS "name",
  pg_catalog.obj_description(c.oid, 'pg_class') AS "comment"
FROM
  pg_class c
WHERE
  c.relkind IN ('r', 'v', 'm') -- only tables (r), views (v), materialized views (m)
  AND c.relnamespace = ANY ($1)
ORDER BY
  c.relnamespace,
  LOWER(relname)
```
aha, it seems `c.relkind in ('r', 'v', 'm')` may change into `c.relkind in ('r', 'v', 'm', 'p')` cause i found the partitioned table's kind is `p`.

**Comment by ozum** [comment]
Hmm, when `p` is added, does it solve the problem?

**Comment by hymanchengo** [comment]
I temporary modified the sql  file under node_modules/pg-structure/module-files/sql/9 and debug, but it seem's doesn't work. Maybe the method I tried was wrong. I am not good at typescript and front-end.Maybe I need to do more study about the code.
since it's late here. maybe i will reply to you tomorrow.Sorry for that!

**Comment by hymanchengo** [comment]
Hi Ozum,
   currently, i fix the problem by modify

**Comment by hymanchengo** [comment]
Hi Ozum,
  so far, I simply modified dist\index.js, and three .sql file in module-files/sql/9/: column.sql.,entity.sql, type.sql
  ```js
function addEntities(db, rows) {
    rows.forEach((row) => {
        const schema = db.schemas.get(row.schemaOid, { key: "oid" });
        /* istanbul ignore else */
        if (row.kind === "r")
            schema.tables.push(new table_1.default({ ...row, schema }));
       // this branch I added
       else if(row.kind === "p" ) {
            schema.tables.push(new table_1.default({ ...row, schema }));
        }
        else if (row.kind === "v")
            schema.views.push(new view_1.default({ ...row, schema }));
        else if (row.kind === "m")
            schema.materializedViews.push(new materialized_view_1.default({ ...row, schema }));
    });
}
  ```

sql fragment modification
``` sql
 SELECT
  c.oid AS "oid",
  c.relnamespace AS "schemaOid",
  c.relkind AS "kind",
  c.relname AS "name",
  pg_catalog.obj_description(c.oid, 'pg_class') AS "comment"
FROM
  pg_class c
WHERE
  c.relkind IN ('r', 'v', 'm', 'p') -- only tables (r), views (v), materialized views (m) i added a 'p' here
  AND c.relnamespace = ANY ($1)
ORDER BY
  c.relnamespace,
  LOWER(relname)
```

i am regeret i didn't pull the request just i can't make it. it's a little hard for me.
the above modification currently seems solved  my problem . but i am not able to do more test.

**Comment by ozum** [comment]
Alright, I'm looking.

**Comment by ozum** [comment]
@hymanchengo thanks for the guidance. I fixed the problem as you explained. I will publish today or tomorrow to npm.
