### ISSUE TITLE
Array dimension not working for views

### ISSUE THREAD

**Issue by Qwerios** [ozum/pg-structure#58]
For some reason the `arrayDimension` value remains 0 for columns in a view. This is making it impossible to detect if I am dealing with arrays in my response. Am I supposed to look elsewhere for views? I've console logged the responses but can't find any attribute on the column and colum.type objects to help me out.

Minimal test sql below. The table returns `arrayDimension =  1` as expected but the view does not.

Is this an unsupported use case or have I hit a bug?

```sql
CREATE TABLE type_check (
    id SERIAL PRIMARY KEY,
    num bigint,
    num_arr bigint[],
    txt text,
    txt_arr text[]
);

CREATE UNIQUE INDEX type_check_pkey ON type_check(id int4_ops);

CREATE VIEW type_check_view AS  SELECT type_check.id,
    type_check.num,
    type_check.num_arr,
    type_check.txt,
    type_check.txt_arr
   FROM type_check;
```

Postgresql 9.6, pg-structure 7.2.1

**Comment by Qwerios** [comment]
![pg_view_dims](https://user-images.githubusercontent.com/254447/95960607-382c0880-0e04-11eb-80dd-d8e8a63aa2f6.png)

This seems to be an issue all the way down in the `pg_catalog`. I've found a SQL clause to detect this issue and set the array dimension to 1. There is no way to detect multi-dimensional arrays this way though it seems. I'm falling back to the sqlType which will only ever show one pair of `[]` I think.

Will make a PR for the SQL fix

**Comment by ozum** [comment]
Many thanks for the PR. I merged and published it with a minor tweak.
