### ISSUE TITLE
Typescript TSD Definitions

### ISSUE THREAD

**Issue by sparebytes** [ozum/pg-structure#6]
Here is my quick and dirty typescript definition files in case anyone else could use it.
https://gist.github.com/sparebytes/5964fa0a41db22ee8a99a6cf7f1f8c3b

I noticed that some places refer to `DB` and others refer to `Db` so I changed everything to use `DB`.

**Comment by ozum** [comment]
Hi,

Thank you for indicating inconsistencies in documentation. Correct one is `Db`. I updated all references consistently as `Db`.

Could you please update your definition.

One more thing. I have no experience on typescript. Should I include definition file to pg-structure and if yes, where?

Also thank you for the contribution.

**Comment by sparebytes** [comment]
Glad to help. I made a pull request for you and tested the changes on my local system. One thing I did was add a dependency to `@types/db`. Some people are inclined to add it to devDependencies instead but that adds extra work for users of your library:

https://github.com/Microsoft/types-publisher/issues/81
