### ISSUE TITLE
Is there anyway to hook into `pg-structure` and add couple of additional queries?

### ISSUE THREAD

**Issue by jayarjo** [ozum/pg-structure#63]
Is there any way to hook into `pg-structure` and add couple of additional queries, mainly for PostGIS? I would gladly do a PR, but I doubt I will be able to research and implement it as exhaustively as you do. So I was looking for a way to extend it somehow after importing into my code.

**Comment by ozum** [comment]
Hi, @jayarjo, I'm afraid this is not possible.
