### ISSUE TITLE
Type 'DK2' does not satisfy the constraint 'keyof I2'

### ISSUE THREAD

**Issue by jayarjo** [ozum/pg-structure#64]
After upgrading to the latest version started to get the following error:

![Screen Shot 2020-11-16 at 12 46 55 PM](https://user-images.githubusercontent.com/150075/99231296-d9deb500-2809-11eb-8621-8903d31c239d.png)

**Comment by jayarjo** [comment]
Any ideas on what might be causing this or how to workaround quickly?

**Comment by jayarjo** [comment]
I replaced:

```
_copyMeta<I2 extends any, DK2 extends DK, OK2 extends OK>(source: IndexableArray<I2, DK2, OK2, any>): this;
```

with:

```
_copyMeta<I2 extends any, DK2 extends DK & keyof I2, OK2 extends OK & keyof I2>(source: IndexableArray<I2, DK2, OK2, any>): this;
```

until there will be a proper fix or recommendation.

Do you think it's ok to have it this way?

**Comment by ozum** [comment]
@jayarjo thank you for your patience, and I'm sorry for being so late. Not a perfect solution, but I relaxed types of `indexable-array` for TypeScript 4. It seems working now. Any further suggestion is appreciated.

Please install the latest version from npm, and it should work with TypeScript 4 as expected.
