### ISSUE TITLE
Missing new data types of Posgresql 14

### ISSUE THREAD

**Issue by rapomon** [ozum/pg-structure#68]
pgStructure causes error in Postgresql 14, it does not recognise the following data types:

- datemultirange
- int4multirange
- int8multirange
- nummultirange
- tsmultirange
- tstzmultirange

More information:
https://www.postgresql.org/docs/14/rangetypes.html

**Comment by ozum** [comment]
@rapomon, Thanks for reporting. PostgreSQL 14 support will be added as soon as possible, but couldn't give a timeframe right now.

**Comment by rapomon** [comment]
Ok. Thank you very much!

**Comment by mmahalwy** [comment]
@ozum bumping this up - any idea on time frame?

**Comment by ozum** [comment]
I published a new version with multi-range support. Please update to the latest version and open a new issue if you see any problem.
