### ISSUE TITLE
jsonschema to postgres?

### ISSUE THREAD

**Issue by magick93** [ozum/pg-structure#74]
Hi

Does `pg-structure` go the other way - from jsonschema to ddl?

Or would you have any advice on how to achieve that?

**Comment by ozum** [comment]
Hi @magick93, unfortunately not. Also, I don't know any method to do that.

**Comment by ingalls** [comment]
I came across: https://github.com/better/jsonschema2db but haven't had time to dive in and give it a go yet.

**Comment by ozum** [comment]
Thanks @ingalls for sharing. @magick93, maybe you can convert jsonschema to db using https://github.com/better/jsonschema2db and later you can use pgdump to create DDL.
