### ISSUE TITLE
In readme file in the section synopsis the property 'host' in the connection object is missing

### ISSUE THREAD

**Issue by gidimetis** [ozum/pg-structure#80]
.
.
.

async function demo() {
  // Prefer to use environment variables or ".env" file for the credentials. See the ".env.example" file.
  const db = await pgStructure({ database: "db", user: "u", password: "pass" }, { includeSchemas: ["public"] });
.
.
.

need to be : const db = await pgStructure({host: "host", database: "db", user: "u", password: "pass" }, { includeSchemas: ["public"] });

**Comment by ozum** [comment]
Thanks for the warning. I fixed it.
