### ISSUE TITLE
Failure in addTriggers in 7.13.1

### ISSUE THREAD

**Issue by stephenh** [ozum/pg-structure#85]
When upgrading from 7.13.1, we are now getting this error:

```
$ yarn codegen
Error: '122524' cannot be found in NormalFunction's oid.
    at Proxy.get (/home/stephen/homebound/graphql-service/node_modules/indexable-array/dist/index.js:491:19)
    at <anonymous> (/home/stephen/homebound/graphql-service/node_modules/pg-structure/dist/main.js:237:35)
    at Array.forEach (<anonymous>)
    at addTriggers (/home/stephen/homebound/graphql-service/node_modules/pg-structure/dist/main.js:235:10)
    at addObjects (/home/stephen/homebound/graphql-service/node_modules/pg-structure/dist/main.js:337:5)
    at pgStructure (/home/stephen/homebound/graphql-service/node_modules/pg-structure/dist/main.js:376:5)
```

If I pin back to 7.13.0, it does not happen.

If I add a `console.log({ row })` right here:

```js
function addTriggers(db, rows) {
    rows.forEach((row) => {
        console.log({row})
        const entity = db.entities.get(row.entityOid, { key: "oid" });
        const func = db.functions.get(row.functionOid, { key: "oid" });
        entity.triggers.push(new trigger_1.default({ ...row, function: func, parent: entity }));
    });
}
```

It shows:

```
{
  row: {
    oid: 222879,
    schemaOid: 2200,
    entityOid: 213901,
    name: 'tr_log_audit_event',
    functionOid: 122524,
    orientation: 'row',
    timing: 'after',
    events: [ 'insert', 'delete', 'update' ],
    condition: null,
    isEnabled: 'origin',
    isDeferrable: false,
    isInitiallyDeferred: false
  }
}
Error: '122524' cannot be found in NormalFunction's oid.
```

The `tr_log_audit_event` is from cyanaudit and looks like:

```
  CREATE TRIGGER tr_log_audit_event
  AFTER INSERT OR UPDATE OR DELETE
  ON activities
  FOR EACH ROW
  EXECUTE PROCEDURE cyanaudit.fn_log_audit_event('{id}', '{97,103,102,98,100,90,101,92,96,99,1875,91}',
  '{activity_definition_id,baseline_end_date,baseline_start_date,enabled,end_date,id,internal_note,name,price_in_cents,start_date,sub_milestone_id,unit_id}');
```

Is that enough to guide to a fix? I can keep poking around at how `db.functions` is populated, and how that changed in 7.13.1, but for now am just going to pin to 7.13.0.

Thanks!

**Comment by ozum** [comment]
Could you please provide a simple DDL (database creation script) and JS code in a GitHub repo that reproduces the error, so I can investigate the problem?

**Comment by ozum** [comment]
@djmarcin, could you please kindly have a look into this? `7.13.1` is committed by your PR related to triggers.

**Comment by stephenh** [comment]
It looks like @djmarcin 's fix is causing this trigger to now get picked up, where as in 7.13.0 it was not.

Which in theory is a good thing, except it also just so happens that this trigger points to a function that exists in a separate schema (the cyanaudit schema), and we're purposefully ignoring the other schema (we're using `includeSchemas: "public"`).

If I hack `addTriggers` to be:

```
function addTriggers(db, rows) {
    rows.forEach((row) => {
        const entity = db.entities.get(row.entityOid, { key: "oid" });
        if (db.functions.has(row.functionOid)) {
            const func = db.functions.get(row.functionOid, { key: "oid" });
            entity.triggers.push(new trigger_1.default({ ...row, function: func, parent: entity }));
        }
    });
}
```

Then it works as it did in 7.13.0.

I dunno, @ozum how do you think this use case of "a trigger pointing to a not-included schema" should be handled? Would you rather keep the 7.13.0 behavior of silently ignoring it? Or force the user to include the schema? (Personally we would prefer to not do that.) Wdyt?

**Comment by ozum** [comment]
@stephenh, good points. Having a trigger pointing to the function in a non-included schema should not be possible in the first place. If this is the case 7.13.0 was silently ignoring the bug. Otherwise, the code below would be possible.

```
// If this points to a non-existing function, it becomes very hard to detect run-time error.
table.triggers[0].function;
```

Throwing an error during the schema traversing is the expected behavior, which helps the developer with the earliest possible warning.

**Comment by stephenh** [comment]
I suppose throwing an error is expected, maybe the error could be more helpful? Like just naively for me it took some digging through pg-structure's source code and putting in console.logs to figure out "oh, it's because the procedure is in a different schema".

Maybe something like:

```
function addTriggers(db, rows) {
    rows.forEach((row) => {
        const entity = db.entities.get(row.entityOid, { key: "oid" });
        if (!db.functions.has(row.functionOid)) {
             throw new Error("Trigger ${...name...} cannot resolve the function ${...oid...}, likely because it is in a different schema");
        }
        const func = db.functions.get(row.functionOid, { key: "oid" });
        entity.triggers.push(new trigger_1.default({ ...row, function: func, parent: entity }));

    });
}```

If you're okay with that, I'm happy to work on a PR, or great if you just want to take care of it. :-)

That said, i.e. even after making the error message nicer, I'm still hoping to get a flag / some sort of behavior change that would let us scan only the `public` schema (since that is really the only tables we're interested in introspecting) and ignore this "the trigger procedure is in a different schema" wrinkle. Would you be open to either of:

1. Changing the `trigger.function` type to be `NormalFunction | undefined`, and letting it be `undefined` for this scenario, or
2. Adding an `Options.skipTriggersWithMissingFunctions`

Or open to other ideas.

**Comment by ozum** [comment]
Agree, the error message should be more informative, but I need to have some more info from @stephenh about the previously committed SQL. It is possible, the error may be caused by a missing function but for the wrong reason. I mean, error may have roots buried deeper than seen.

Also having an `if` statement in `addTriggers` function seems a non-generic solution. After @stephenh answer, I should think of a more generic solution to this problem, because other types of objects throw errors for missing objects.

> 1. Changing the trigger.function type to be NormalFunction | undefined, and letting it be undefined for this scenario, or
> 2. Adding an Options.skipTriggersWithMissingFunctions

Previously we experimented with this (started with FK-referenced tables in ignored schemas), but it causes lots of edge cases very hard to debug and maintain. Later, we decided to stick what DBMS does and throw hard when something is missing. It is much easier to include all schemas and not use non-needed parts.

**Comment by stephenh** [comment]
> error may be caused by a missing function but for the wrong reason.
> I mean, error may have roots buried deeper than seen.

That's true, my proposed "better error message" was guessing about the reason why the `oidFunction` was missing, without really knowing that it was 100% because it was in a separate schema.

> It is much easier to include all schemas and not use non-needed parts.

Yeah that makes sense.

I'll update our code to account for that. Thanks!
