### ISSUE TITLE
Support generated columns

### ISSUE THREAD

**Issue by nick-keller** [ozum/pg-structure#88]
Hello, awesome library!
I realised that there is no way today to know if a colummn is [generated](https://www.postgresql.org/docs/current/ddl-generated-columns.html) or not.

In PG, within the `columns` view, we have the `is_generated` column (`NEVER` = normal, `ALWAYS` = generated) and the `generation_expression` column (`NULL` = not generated, anything else = how is the column generated).

That would be nice to be able to access this from the [`Column`](https://www.pg-structure.com/nav.02.api/classes/column.html) class.

Is this planned / blocked ? Are you open to contributions ?

**Comment by ozum** [comment]
@nick-keller Thanks for the suggestion. I added `column.isGenerated`. It will be published to the npm after CI is finished.

**Comment by nick-keller** [comment]
Amazing, thx @ozum !
