### ISSUE TITLE
Inability to get another schemes different from 'public'

### ISSUE THREAD

**Issue by RagazziMoscow** [ozum/pg-structure#9]
Hi
I am trying to get structure of my database with 3 schemes. The module work correctly only with 'public' scheme. In another schemes it does not discover any tables. It would be useful if it has ability to analyze another schemes correctly.

**Comment by ozum** [comment]
Hi,
It already supports schemas. Could you please provide a short code sample. I will correct if there is a bug.

Kind Regards,




On Thu, Mar 2, 2017 at 9:13 PM +0300, "Dragan" <notifications@github.com> wrote:












Hi

I am trying to get structure of my database with 3 schemes. The module work correctly only with 'public' scheme. In another schemes it does not discover any tables. It would be useful if it has ability to analyze another schemes correctly.

**Comment by RagazziMoscow** [comment]
I need to get the structure and its tables:

var pgStructure = require('pg-structure');

var connectionArgs = {
  database: "Example",
  user: "admin",
  password: "admin",
  host: "localhost",
  port: 5432
};

pgStructure(connectionArgs, ['public', 'cekavo'])
  .then((db) => {
    console.log(db.get('public').tables);
  })
  .catch(err => console.log(err.stack));

For public schema it works correctly but when i am trying to see the structure of another schema it returns an emty map object:
AMap {}
For another databases when i include in array another schemes i watch the TypeError:
TypeError: Cannot read property 'name' of undefined

P.S.: I am using library installed by npm.

**Comment by ozum** [comment]
Hi,

I created a sample schema and tested and it seems working. Also library has tests for multiple schema in https://github.com/ozum/pg-structure/blob/master/test/002-schema.js

I shared a schema and code below. Could you please check if it is working for you?

Also if you share your two database schemas (the one with empty map object and other one with  type error), I can check and verify them for you too. If there is a hidden bug in `pg-structure`, I happily fix it.

Regards,

```js
var pgStructure = require('pg-structure');

const connectionArgs = {database: 'searcher', user: 'user', password: 'password'};

pgStructure(connectionArgs, ['public', 'deneme'])
  .then((db) => { console.log( db.get('deneme').tables ); })
  .catch(err => console.log(err.stack));
```


```sql
CREATE SCHEMA deneme;
SET check_function_bodies = false;

SET search_path = public, pg_catalog;
CREATE TABLE public."Account" (
    id serial NOT NULL,
    "legalName" varchar(20),
    "ownerId" integer,
    "primaryContactId" integer
)
WITH (oids = false);

CREATE TABLE public."Contact" (
    id serial NOT NULL,
    "firstName" varchar(20),
    "accountId" integer
)
WITH (oids = false);

CREATE TABLE public."Region" (
    id serial NOT NULL,
    name varchar(20)
)
WITH (oids = false);

CREATE TABLE public."AccountRegion" (
    "accountId" integer NOT NULL,
    "regionId" integer NOT NULL,
    priority integer
)
WITH (oids = false);

SET search_path = deneme, pg_catalog;
CREATE TABLE deneme.other_table (
    id serial NOT NULL
)
WITH (oids = false);

SET search_path = public, pg_catalog;
CREATE INDEX "IX_Owner" ON "Account" USING btree ("ownerId");

CREATE INDEX "IX_PrimaryContact" ON "Account" USING btree ("primaryContactId");

CREATE INDEX "IX_AccountContacts" ON "Contact" USING btree ("accountId");

ALTER TABLE ONLY "Account"
    ADD CONSTRAINT "Keyaccount1"
    PRIMARY KEY (id);

ALTER TABLE ONLY "Contact"
    ADD CONSTRAINT "Keycontact1"
    PRIMARY KEY (id);

ALTER TABLE ONLY "Region"
    ADD CONSTRAINT "KeyRegion1"
    PRIMARY KEY (id);

ALTER TABLE ONLY "AccountRegion"
    ADD CONSTRAINT "KeyAccountRegion1"
    PRIMARY KEY ("regionId", "accountId");

ALTER TABLE ONLY "Contact"
    ADD CONSTRAINT "AccountContacts"
    FOREIGN KEY ("accountId") REFERENCES "Account"(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "AccountRegion"
    ADD CONSTRAINT "AccountRegions"
    FOREIGN KEY ("accountId") REFERENCES "Account"(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "AccountRegion"
    ADD CONSTRAINT "RegionAccounts"
    FOREIGN KEY ("regionId") REFERENCES "Region"(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "Account"
    ADD CONSTRAINT "OwnerCompanies"
    FOREIGN KEY ("ownerId") REFERENCES "Contact"(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE ONLY "Account"
    ADD CONSTRAINT "PrimaryContactCompanies"
    FOREIGN KEY ("primaryContactId") REFERENCES "Contact"(id) ON UPDATE CASCADE ON DELETE CASCADE;

SET search_path = deneme, pg_catalog;
ALTER TABLE ONLY other_table
    ADD CONSTRAINT other_table_pkey
    PRIMARY KEY (id);

```

**Comment by RagazziMoscow** [comment]
I uploaded my schema on that i got the TypeError:
https://github.com/RagazziMoscow/db_schema.git
As far as schemas on which it returns an empty map object, it don't see the tables without primary keys.

P.S.: I learned the schema on which i gave the link that there is structure of hierarchic three placed in relational database. So, i think it is ok that the library doesn't support this schema ))

**Comment by ozum** [comment]
Hi,

I fixed the bug.

Bug was subtle and hard to track, but had high impact in some scenarios: If same constraint name is used in same database schema, `pg-structure` was failing. I updated necessary sql query. So it should work as expected.

You can use it with your database.

Thanks for reporting.

Kind regards,

**Comment by RagazziMoscow** [comment]
Yes, it works. Tnank )
