### ISSUE TITLE
Dependency on indexable-array causing high severity security alert

### ISSUE THREAD

**Issue by davekerber** [ozum/pg-structure#91]
Starting about two weeks ago I now get this warning from npm: 

lodash.set  *
Severity: high
Prototype Pollution in lodash - https://github.com/advisories/GHSA-p6mc-m468-83gw
No fix available
node_modules/lodash.set
  indexable-array  *
  Depends on vulnerable versions of lodash.set
  node_modules/indexable-array
    pg-structure  >=5.1.0
    Depends on vulnerable versions of indexable-array
    node_modules/pg-structure

My actual installed version of pg-structure is 7.15.0

It's an old advisory but it looks like the affected versions changed two weeks ago: https://github.com/github/advisory-database/commit/750e8505274d5f54b1c27ecd5cc029b8170d8154

**Comment by stephenh** [comment]
Hey @ozum , I thought the issue was just in `pg-structure`, and was prepping a PR to remove the AFAICT-unused `lodash.get` dependency from the project, for a quick win.

...but turns out the warning is actually on `lodash.set`, from `indexable-array`.

It looks like lodash has stopped publishing the `lodash.*` packages, so will have to switch `indexable-array` over to that...

Are you fine with that? If so, I'll submit a PR. Thanks!

**Comment by ozum** [comment]
Thanks, @davekerber and @stephenh.

@stephenh `indexable-array` uses an ancient DevOps framework and may be hard to release, so I don't want to bother you with a PR. I updated `indexable-array` and got rid of `lodash.set`.

I also updated `pg-structure` to use the new version of `indexable-array`. Please install the latest version of pg-structure. I hope this will solve the problem.

**Comment by davekerber** [comment]
@ozum, thank you for looking at this so quickly! After updating I still see the warning. It looks like all the code referencing `lodash.set` has been removed from `indexable-array` but the dependency is still in the package.json 

https://github.com/ozum/indexable-array/blob/master/package.json#L54

and 

https://github.com/ozum/indexable-array/blob/master/package.json#L61

and is still showing in the dependencies: https://www.npmjs.com/package/indexable-array/v/0.7.3?activeTab=dependencies

**Comment by ozum** [comment]
oh my... I forgot to uninstall it.

Now, it should be fixed.

**Comment by davekerber** [comment]
Can confirm it's resolved. Thanks @ozum!

**Comment by stephenh** [comment]
Awesome! Thanks @ozum !
